Integrated generators into unheated surface report
therealmonE/fire-res pull request #114
Opened 2021-02-06 14:46 UTC by Jaxor1337

Closes #106

2021-02-06 14:47 UTC, kast55ru approved these changes

2021-02-07 08:43 UTC, therealmonE requested changes

2021-02-07 08:43 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/controller/unheated/surface/thermocouple/groups/first/thermocouple/group/FirstThermocoupleGroupParamsController.java
> +    private void handleFirstThermocoupleGroupNumberOfThermocouplesSpinnerFocusChanged(Boolean focusValue) {
не надо в названии метода указывать, к какой группе относится обработчик. Сделай плз handleThermocouplesCountSpinnerFocusChanged

2021-02-07 08:43 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/controller/unheated/surface/thermocouple/groups/second/thermocouple/group/SecondThermocoupleGroupParamsController.java
> +                handleSecondThermocoupleGroupNumberOfThermocouplesSpinnerFocusChanged(newValue));
same

2021-02-07 08:43 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/controller/unheated/surface/thermocouple/groups/second/thermocouple/group/SecondThermocoupleGroupParamsController.java
> +                handleSecondThermocoupleGroupBoundSpinnerFocusChanged(newValue));
same

2021-02-07 08:43 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/controller/unheated/surface/thermocouple/groups/third/thermocouple/group/ThirdThermocoupleGroupParamsController.java
> +                handleThirdThermocoupleGroupNumberOfThermocouplesSpinnerFocusChanged(newValue));
same

2021-02-07 11:42 UTC, therealmonE approved these changes

2021-02-07 11:43 UTC, kast55ru approved these changes

2021-02-07 11:45 UTC, merged