Added new default font / Fixed font bug
therealmonE/fire-res pull request #137
Opened 2021-02-13 13:20 UTC by Jaxor1337

Closes #134 
Closes #135

2021-02-13 13:21 UTC, kast55ru submitted a review, later dismissed

2021-02-14 11:52 UTC, therealmonE requested changes

2021-02-14 11:52 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/controller/MainSceneController.java
> +        InputStream defaultFont = getClass().getResourceAsStream("/font/OpenSans-Bold.ttf");
Надо убрать

2021-02-14 11:58 UTC, therealmonE approved these changes

2021-02-14 12:20 UTC, kast55ru approved these changes

2021-02-14 12:21 UTC, merged