Feature/fireres 190
therealmonE/fire-res pull request #192
Opened 2021-04-17 12:17 UTC by asku4

Closes #190

2021-04-17 12:28 UTC, therealmonE requested changes
Поправь комменты плз

2021-04-17 12:28 UTC, therealmonE commented on core/src/main/java/io/github/therealmone/fireres/core/config/FunctionForm.java
> +import lombok.*;
Убери у себя в настройках идеи * импорты плз, и раскрой этот импорт

2021-04-17 12:28 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/GuiModule.java
> +import io.github.therealmone.fireres.gui.configurer.report.*;
same

2021-04-17 12:28 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/GuiModule.java
> +import io.github.therealmone.fireres.gui.service.*;
same

2021-04-17 12:28 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/GuiModule.java
> +    public static final Class[] REPORT_PROPERTIES_CLASSES = new Class[]{
зачем удалила пробел?)

2021-04-17 12:28 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/controller/modal/SampleSavePresetModalWindow.java
> +    ApplicationConfig applicationConfig;
private

2021-04-17 12:28 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/controller/modal/SampleSavePresetModalWindow.java
> +    @FXML
пробелы между филдами

2021-04-17 12:28 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/controller/modal/SampleSavePresetModalWindow.java
> +@ModalWindow(title = "Сохранить как пресет")
Лучше "Сохранение пресета"

2021-04-17 12:28 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/controller/modal/SampleSavePresetModalWindow.java
> +            Preset newPreset = new Preset();
можно заменить на билдер:
Preset.builder()
.field1()
.field2()
.build()

2021-04-17 12:28 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/controller/modal/SampleSavePresetModalWindow.java
> +            presetService.savePreset(newPreset, applicationConfig.getCustomPresetsPath() + "/custom_preset_" + UUID.randomUUID() + ".json");
Перенеси формирование названия файла прям в PresetService

2021-04-17 12:28 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/service/impl/PresetServiceImpl.java
> +        BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(new File(path)));
try with resources нужен, зачем вручную вызываешь close() ?

2021-04-17 12:28 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/service/impl/PresetServiceImpl.java
> +        BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(new File(path)));
Так же, у тебя bufferedWriter, надо в конце еще flush() вызывать

2021-04-17 12:28 UTC, therealmonE commented on presets/custom/custom_preset_3213fba2-8326-4037-9920-b65d41db552a.json
> +{"applyingByDefault":false,"description":"custom","properties":{"io.github.therealmone.fireres.heatflow.config.HeatFlowProperties":{"_class":"io.github.therealmone.fireres.heatflow.config.HeatFlowPro
Попробуй сделать так, чтобы сохранялось в pretty формате (то есть с переносами, вроде прям у сериализатора можно как-то указать это)

2021-04-17 12:30 UTC, asku4 commented on gui/src/main/java/io/github/therealmone/fireres/gui/GuiModule.java
> +    public static final Class[] REPORT_PROPERTIES_CLASSES = new Class[]{
ctrl+alt+L))

2021-04-17 12:37 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/controller/modal/SampleSavePresetModalWindow.java
> +            presetService.getAvailablePresets().add(newPreset);
Это тоже надо перенести в реализацию метода savePreset()

2021-04-17 13:07 UTC, asku4 commented on gui/src/main/java/io/github/therealmone/fireres/gui/GuiModule.java
> +    public static final Class[] REPORT_PROPERTIES_CLASSES = new Class[]{
ctrl + alt + L)

2021-04-18 09:42 UTC, therealmonE requested changes

2021-04-18 09:42 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/service/PresetService.java
> +    void savePreset(Boolean applyingByDefault, String description, Map<Class<? extends ReportProperties>, ReportProperties> properties) throws IOException;
поменяй сигнатуру на savePreset(Preset preset) плз

2021-04-18 09:42 UTC, therealmonE commented on gui/src/main/java/io/github/therealmone/fireres/gui/service/impl/PresetServiceImpl.java
> +            val objectMapper = new ObjectMapper();
не надо маппер собирать самому, заинжекти его

2021-04-18 18:52 UTC, therealmonE approved these changes

2021-04-18 19:37 UTC, merged

2021-04-18 19:41 UTC, asku4 commented
Затрачено: 8ч